### ISSUE TITLE
Add basic device source list parser

### ISSUE THREAD

**Issue by rbagrov** [rbagrov/xana#2]
**Background:**

Devices need to be grouped and feeded as a list for ad-hoc connect.

**Tasks:**

- [x] Create directory device groupset
- [x] Set naming convention
- [x] Create walker which calls each parser class based filetype
- [x] Add ini parser
- [x] Add json parser
- [x] Add yaml parser
- [x] Add xml parser
