### ISSUE TITLE
Telnet client

### ISSUE THREAD

**Issue by rbagrov** [rbagrov/xana#4]
**Background:**

There have to be telnet client available if API for each xanin

**Tasks:**

- [x] Add datatype validator
- [x] Set naming
- [x] Design class
- [x] Add Telnet connection method
- [x] Add Telnet write method
