### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by rbagrov** [rbagrov/xana#6]
**Background:**

Proper logging has to be implemented

**Tasks:**

- [x] Add custom logger
- [x] Add no debug argument
- [x] Add set custom formatter
- [x] Add proper exception handling in current code
