### ISSUE TITLE
Init basic versioning algorithm

### ISSUE THREAD

**Issue by rbagrov** [rbagrov/xana#8]
**Background**

For basic operation, this tool have to be able to:

**Tasks**

- [ ] Identify which xanin to use;
- [ ] Try all possible connection methods;
- [ ] Download current configuration;
- [ ] Set metadata for downloaded configuration (version_tag, device_brand, device_id, datetime, size)
- [ ] Write the configuration and metadata to mongodb;
- [ ] Define upgrade algorithm;
- [ ] Deploy upgrade tag to target device;
- [ ] Define downgrade algorithm;
- [ ] Deploy downgrade tag to target device;
